### ISSUE TITLE
ArgumentOutOfRangeException exception version 3.1.0

### ISSUE THREAD

**Issue by karthikr-vti** [Cysharp/ObservableCollections#80]
I noticed a similar issue in case #70 , which has since been resolved. However, I'm still encountering ArgumentOutOfRangeException with version 3.1.0 sporadically when collections are cleared and re-added. I'll try to work on isolating the problem

```
System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection. (Parameter 'index')
   at ObservableCollections.FiltableSynchronizedViewList`2.get_Item(Int32 index)
   at ObservableCollections.NotifyCollectionChangedSynchronizedViewList`2.System.Collections.IList.get_Item(Int32 index)
   at DevExpress.Xpf.Editors.Helpers.PlainDataView.ProcessAddItem(Int32 index)
   at DevExpress.Xpf.Editors.Helpers.DataView.ProcessChangeSource(ListChangedEventArgs e)
   at DevExpress.Xpf.Editors.Helpers.DataController.ItemsSourceListChanged(Object sender, ListChangedEventArgs e)
   at DevExpress.Data.Utils.WeakEventHandler`3.OnEvent(Object source, TEventArgs eventArgs)
   at DevExpress.Data.Helpers.BindingListAdapterBase.OnSourceCollectionChanged(Object sender, NotifyCollectionChangedEventArgs e)
   at DevExpress.Data.Utils.WeakEventHandler`3.OnEvent(Object source, TEventArgs eventArgs)
   at ObservableCollections.NotifyCollectionChangedSynchronizedViewList`2.RaiseChangedEvent(NotifyCollectionChangedEventArgs e)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
   at MS.Internal.CulturePreservingExecutionContext.CallbackWrapper(Object obj)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
```

**Comment by neuecc** [comment]
Thank you, I'll check it out.
It seems to be going through binding, but could you give me a simple Add/Remove process?

**Comment by karthikr-vti** [comment]
Thank you for your response. I was unable to reproduce this issue with the latest version 3.2.0. I’ll go ahead and close this issue for now

**Comment by karthikr-vti** [comment]
I can now reproduce the problem. It appears to be specific to WPF and is caused by posting values from different threads. I'm attaching the project that demonstrates this issue. Thank you for looking into it!

[obstest.zip](https://github.com/user-attachments/files/18047647/obstest.zip)
